format block device during creation

diff --git a/package/ebs/rancher-ebs b/package/ebs/rancher-ebs
--- a/package/ebs/rancher-ebs
+++ b/package/ebs/rancher-ebs
@@ -51,41 +51,6 @@ wait_volume_attaching() {
     fi
 }
 
-# TODO remove dead code unless we find a use for this
-detach_if_attached(){
-    local volumes
-    local instance_status
-    local error
-    volumes=`aws ec2 describe-volumes --region ${EC2_REGION} --volume-ids ${VOLUME_ID} 2>&1`
-    if [ $? -ne 0 ]; then
-        print_error "Failed in attach: ${volumes}"
-    fi
-
-    # get attached instance id
-    local attached_instance_id=$(echo ${volumes} | jq -r '.Volumes[0].Attachments[0].InstanceId')
-
-    # check if volumeID is already attached to another instance
-    if [ "${attached_instance_id}" != "null" ]; then
-        instance_status=`aws ec2 describe-instance-status --region ${EC2_REGION} --instance-ids ${attached_instance_id} 2>&1`
-        if [ $? -ne 0 ]; then
-            print_error "Failed in attach: ${instance_status}"
-        fi
-
-        # if currently attached instance VM is running, we can't detach, error out here
-        local status=$(echo ${instance_status} | jq -r '.InstanceStatuses[0].InstanceState.Name')
-        if [ "${status}" == "running" ] && [ "${attached_instance_id}" != "${INSTANCE_ID}" ]; then
-            print_error "Failed: volume ${VOLUME_ID} is currently attached to a running instance ${attached_instance_id}, can not detach or re-use it"
-        fi
-
-        # detach it from currently attached instance VM
-        error=`aws ec2 detach-volume --region ${EC2_REGION} --volume-id ${VOLUME_ID} --instance-id ${attached_instance_id} 2>&1`
-        if [ $? -ne 0 ]; then
-            print_error "Failed to detach ebs volume-id ${VOLUME_ID} from instance-id ${attached_instance_id}. ${error}"
-        fi
-        wait_volume_transition "in-use" "available"
-    fi
-}
-
 find_available_device_path() {
     local attachments
     attachments=`aws ec2 describe-volumes --region ${EC2_REGION} --filters Name=attachment.instance-id,Values=${INSTANCE_ID} | jq -r '.Volumes[].Attachments[]'`
@@ -179,7 +144,126 @@ create() {
         print_error "Failed in create: create-tags for volume ${VOLUME_ID} Key=Name,Value=${OPTS[name]} failed. ${error}"
     fi
 
+    local device_path=$(do_attach)
+
+    error=`mkfs.ext4 -F $device_path 2>&1`
+    if [ $? -ne 0 ]; then
+        print_error $error
+    fi
+
+    do_detach $device_path
+
     print_options created true volumeID ${VOLUME_ID}
+}
+
+is_attached() {
+    local aws_device_path=$1
+    # from device, get VOLUME_ID
+    local attachments
+    attachments=`aws ec2 describe-volumes --region ${EC2_REGION} --filters Name=attachment.instance-id,Values=${INSTANCE_ID} | jq -r '.Volumes[].Attachments[]'`
+    if [ $? -ne 0 ]; then
+        print_error "Failed to describe volume of instance-id ${INSTANCE_ID}. ${attachments}"
+    fi
+
+    VOLUME_ID=`echo ${attachments} | jq "select(.Device==\"${aws_device_path}\") | .VolumeId"`
+    VOLUME_ID=`echo ${VOLUME_ID=} | sed -e 's/^"//' -e 's/"$//'`
+
+    if [ -z "${VOLUME_ID}" ]; then
+        return 1
+    else
+        return 0
+    fi
+}
+
+do_attach() {
+    local device_path=$(find_available_device_path)
+    while [ "$device_path" != "" ]; do
+        error=`aws ec2 attach-volume --region ${EC2_REGION} --volume-id ${VOLUME_ID} --instance-id ${INSTANCE_ID} --device ${device_path} 2>&1`
+        if [ $? -ne 0 ]; then
+            if [ "$(echo $error | grep 'already in use')" ]; then
+                # another mount snagged our device_path, try again
+                device_path=$(find_available_device_path)
+                continue
+            # unrecoverable error
+            else
+                print_error "Failed to attach ebs volume-id ${VOLUME_ID} as device:${device_path} to aws instance-id ${INSTANCE_ID}. ${error}"
+            fi
+        else
+            wait_volume_attaching
+            echo $(find_matching_linux_device_path "${device_path}")
+            break
+        fi
+    done
+}
+
+do_detach() {
+    local error
+    error=`aws ec2 detach-volume --region ${EC2_REGION} --volume-id ${VOLUME_ID} 2>&1`
+    if [ $? -ne 0 ]; then
+        print_error "Failed to detach ebs volume-id ${VOLUME_ID} from current instance. ${error}"
+    fi
+    wait_volume_transition "in-use" "available"
+}
+
+attach() {
+    if [ -z "${OPTS[volumeID]}" ]; then
+        print_error "volumeID is required"
+    fi
+
+    VOLUME_ID=${OPTS[volumeID]}
+
+    unset_aws_credentials_env
+
+    get_meta_data
+
+    local linux_device_path=$(do_attach)
+
+    if [ "$linux_device_path" != "" ]; then
+        print_device ${linux_device_path}
+    else
+        print_error All device paths are in use for instance-id: ${INSTANCE_ID}
+    fi
+}
+
+detach() {
+    local aws_device_path="/dev/sd""${DEVICE: -1}"
+
+    unset_aws_credentials_env
+
+    get_meta_data
+
+    is_attached $aws_device_path
+    if [ $? -eq 0 ]; then
+        do_detach
+    fi
+
+    print_success
+}
+
+mountdest() {
+    local error
+
+    error=`mount $DEVICE $MNT_DEST 2>&1`
+    if [ $? -ne 0 ]; then
+        print_error $error
+    fi
+
+    print_success
+}
+
+unmount() {
+    local result
+    result=`umount $MNT_DEST 2>&1`
+    if [ $? -ne 0 ]; then
+        if [ "$(echo $result | grep 'not mounted')" ]; then
+            print_success not mounted
+        elif [ "$(echo $result | grep 'mountpoint not found')" ]; then
+            print_success not found
+        else
+            print_error $result
+        fi
+    fi
+    print_success unmounted
 }
 
 delete() {
@@ -201,7 +285,12 @@ delete() {
     local volumes
     volumes=`aws ec2 describe-volumes --region ${EC2_REGION} --volume-ids ${VOLUME_ID} 2>&1`
     if [ $? -ne 0 ]; then
-        print_error "Failed to describe volume ${VOLUME_ID}: ${volumes}"
+        if [ "$(echo $error | grep 'InvalidVolume.NotFound')" ]; then
+            print_success Volume not found
+            exit 0
+        else
+            print_error "Failed to describe volume ${VOLUME_ID}: ${volumes}"
+        fi
     fi
 
     current_state=$(echo ${volumes} | jq -r '.Volumes[0].State')
@@ -213,113 +302,14 @@ delete() {
     error=`aws ec2 delete-volume --region ${EC2_REGION} --volume-id ${VOLUME_ID} 2>&1`
     if [ $? -ne 0 ]; then
         if [ "$(echo $error | grep 'InvalidVolume.NotFound')" ]; then
-            print_success "not found"
+            print_success Volume not found
+            exit 0
         else
             print_error "Failed to delete volume ${VOLUME_ID}. ${error}"
         fi
     fi
 
     print_success
-}
-
-attach() {
-    print_not_supported
-}
-
-detach() {
-    local aws_device_path="/dev/sd""${DEVICE: -1}"
-
-    unset_aws_credentials_env
-
-    get_meta_data
-
-    # from device, get VOLUME_ID
-    local attachments
-    attachments=`aws ec2 describe-volumes --region ${EC2_REGION} --filters Name=attachment.instance-id,Values=${INSTANCE_ID} | jq -r '.Volumes[].Attachments[]'`
-    if [ $? -ne 0 ]; then
-        print_error "Failed to describe volume of instance-id ${INSTANCE_ID}. ${attachments}"
-    fi
-
-    VOLUME_ID=`echo ${attachments} | jq "select(.Device==\"${aws_device_path}\") | .VolumeId"`
-    VOLUME_ID=`echo ${VOLUME_ID=} | sed -e 's/^"//' -e 's/"$//'`
-
-    # no such device attached
-    if [ -z "${VOLUME_ID}" ]; then
-        print_success
-        exit 0
-    fi
-
-    local error
-    error=`aws ec2 detach-volume --region ${EC2_REGION} --volume-id ${VOLUME_ID} 2>&1`
-    if [ $? -ne 0 ]; then
-        print_error "Failed to detach ebs volume-id ${VOLUME_ID} from current instance. ${error}"
-    fi
-    wait_volume_transition "in-use" "available"
-
-    print_success
-}
-
-mountdest() {
-    local error
-
-    if [ -z "${OPTS[volumeID]}" ]; then
-        print_error "volumeID is required"
-    fi
-
-    VOLUME_ID=${OPTS[volumeID]}
-
-    unset_aws_credentials_env
-
-    get_meta_data
-
-    while true; do
-        local device_path=$(find_available_device_path)
-
-        error=`aws ec2 attach-volume --region ${EC2_REGION} --volume-id ${VOLUME_ID} --instance-id ${INSTANCE_ID} --device ${device_path} 2>&1`
-        if [ $? -ne 0 ]; then
-            # another mount snagged our device_path
-            if [ "$(echo $error | grep 'already in use')" ]; then
-                continue
-            # unrecoverable error
-            else
-                print_error "Failed to attach ebs volume-id ${VOLUME_ID} as device:${device_path} to aws instance-id ${INSTANCE_ID}. ${error}"
-            fi
-        else
-            break
-        fi
-    done
-
-    wait_volume_attaching
-
-    # need to return real linux device path, it could be in a different format "sdf" => "xvdf"
-    local linux_device_path=$(find_matching_linux_device_path "${device_path}")
-
-    error=`mkfs.ext4 -F $linux_device_path 2>&1`
-    if [ $? -ne 0 ]; then
-        print_error $error
-    fi
-
-    error=`mount $linux_device_path $MNT_DEST 2>&1`
-    if [ $? -ne 0 ]; then
-        print_error $error
-    fi
-
-    print_success
-}
-
-unmount() {
-    local result
-    result=`umount $MNT_DEST 2>&1`
-    if [ $? -ne 0 ]; then
-        if [ "$(echo $result | grep 'not mounted')" ]; then
-            print_success not mounted
-        elif [ "$(echo $result | grep 'mountpoint not found')" ]; then
-            print_success not found
-        else
-            print_error $result
-        fi
-    fi
-    print_success unmounted
 }
 
 # Every script must call main as such
